apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: local-pipeline
spec:
  vertices:
    - name: in
      source:
        http : {}
    - name: even-or-odd
      scale:
        min: 1
      udf:
        container:
          image: quay.io/yhl25/even-odd:v0.0.3
    - name: even-sink
      scale:
        min: 1
      sink:
        # A simple log printing sink
        log: {}
    - name: odd-sink
      scale:
        min: 1
      sink:
        log: {}
    - name: number-sink
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: even-or-odd
    - from: even-or-odd
      to: even-sink
      conditions:
        tags:
          values:
            - even-tag
    - from: even-or-odd
      to: odd-sink
      conditions:
        tags:
          operator: or
          values:
            - odd-tag
    - from: even-or-odd
      to: number-sink
      conditions:
        tags:
          operator: and
          values:
            - even-tag
            - odd-tag
